name: Build and Deploy on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy code to DigitalOcean
        run: |
          ssh ${{ varibles.LIN_USER }}@${{ variables.LIN_IP }} 'mkdir -p ~/coinbitly'
          scp -i "${{ secrets.SSH_PRIVATE_KEY_PATH }}" -r ./* ${{ varibles.LIN_USER }}@${{ variables.LIN_IP }}:~/coinbitly/

      - name: Build and Deploy on DigitalOcean
        run: |
          ssh ${{ varibles.LIN_USER }}@${{ variables.LIN_IP }} '
            cd ~/coinbitly
            docker build -t golang-app .
            docker run -d -p 35259:35259 --name golang-app golang-app
          '

      - name: Clean up uploaded code
        run: ssh ${{ varibles.LIN_USER }}@${{ variables.LIN_IP }} 'rm -rf ~/coinbitly/*'
