name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Go Application and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.21.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
 
      - name: Build Go Application
        run: go build -o coinbitly .

      - name: Docker Login
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker tag chidi150c/golang21conbitly:${{ github.sha }} chidi150c/golang21conbitly:${{ github.sha }}
          docker push chidi150c/golang21conbitly:${{ github.sha }}

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            # Stop and remove containers with specific labels
            docker stop $(docker ps -q -f name=golang21conbitly) || true
            docker rm $(docker ps -aq -f name=golang21conbitly) || true

            # Remove images with specific labels
            docker rmi $(docker images -q chidi150c/golang21conbitly) || true

            docker pull chidi150c/golang21conbitly:${{ github.sha }}
            docker run -d -p 35259:35259 --name golang21conbitly chidi150c/golang21conbitly:${{ github.sha }}  
            sudo systemctl restart nginx
