name: Go Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Go Application and Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
 
      - name: Build Go Application
        run: |
          go clean -modcache
          go get -u ./...  
          go build -o conbitly .

      - name: Docker Login
        run: |
          docker logout
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./
          dockerfile: Dockerfile
          push: true
          tags: chidi150c/golong17conbitly:${{ github.sha }}

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          key_type: rsa
          script: |
            # docker logout  # Optional: Only if Docker login is needed for pulling new image
            # docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Stop and remove containers with specific labels
            docker stop $(docker ps -q -f name=golong17conbitly) || true
            docker rm $(docker ps -aq -f name=golong17conbitly) || true

            # Remove images with specific labels
            docker rmi $(docker images -q chidi150c/golong17conbitly) || true

            docker pull chidi150c/golong17conbitly:${{ github.sha }}
            docker run -d -p 35260:35260 --name golong17conbitly chidi150c/golong17conbitly:${{ github.sha }}  
            sudo systemctl restart nginx
